### ISSUE TITLE
SizeInt class does not exist

### ISSUE THREAD

**Issue by ddwalters** [DavidSouzaLD/InventoryTetris-Unity#2]
Hey David, I'm looking into this repository and would love to test it out on my own! I've attempted to use your scripts in a unity project but don't have the class for 'SizeInt' which can be found in ItemData. Was this a file you used in your project that you did not include in the repository? Otherwise if this is an import I'd love to know! I'm using unity version 2023.1.7f incase this has any impact.

**Comment by KiosumaDev** [comment]
Yes i have the same problem i guess a SizeInt is maybe basicly a Vector2 of int ? 

I create that : 
`public class SizeInt
{
    public SizeInt(int x = 0, int y = 0)
    {
        height = y;
        width = x;
    }
    public int height = 0;
    public int width = 0;
}`
I guess is fix the problem

**Comment by ddwalters** [comment]
Either a vector2 or a class simply containing two int variables for height and width. I attempted to make one that way but ran into problems. No items would load onto the grid. Not sure if this is because of my makeshift class but I ran out of time that day to keep testing. 

I'll test more tomorrow to hopefully make some progress! This system seems well written so getting past these few hurdles and replacing my current (very overly-complicated) system would be awesome.

**Comment by ddwalters** [comment]
> Yes i have the same problem i guess a SizeInt is maybe basicly a Vector2 of int ?
> 
> I create that : `public class SizeInt { public SizeInt(int x = 0, int y = 0) { height = y; width = x; } public int height = 0; public int width = 0; }` I guess is fix the problem

Finally got some time today to test some stuff out.
```
[Serializable]
public class SizeInt
{
    public int width;

    public int height;

    public SizeInt(int width, int height)
    {
        this.width = width;
        this.height = height;
    }
}
```

This class here is a good replacement for it! The whole system worked well for me after adding it.
